### PR TITLE
Intitial build tool setup

### PR DESCRIPTION
**Pull request by RedRiderX**
I've finished some initial setup for build tools.

`npm start` will compile and watch sass and js and start BrowserSync. Other commands can be found in the `package.json` file I've added.

I also moved the `fonts` directory out of `stylesheets` to work with sass importing. I'm not sure if the automatic merge will pick up on that so you may need to clear out the old fonts location.

Again if any of this seems questionable let me know and I can change it.

### CODE REVIEW

**Comment by enthusiast94** [comment]
I just created a dev branch and updated the theme to card layout there (similar to google inbox). Maybe we should work on dev branch for now and then push changes to master later.

**Comment by enthusiast94** [comment]
Hi Red, great work on the build tools! They definitely have made the development process a lot faster. Thanks!

**Comment by enthusiast94** [comment]
Hi there again! After some prolonged testing, I realized that css and js being built after every change was really slowing down development. Also, I actually prefer refreshing the browser window when I make changes rather than auto-refreshing it on every change, therefore I've reverted the merge. In the new build process, I've set up two npm scripts: 'start' and 'build'. 'npm start' will start up an http server on port 3000, while 'npm build' will minify all js modules. Now the only dev-dependency is 'htp-server'. I'll update the documentation soon.

**Comment by RedRiderX** [comment]
Ah good move.

I see you are still committing on the master branch, do you still plan on using dev as the main branch with master as the release branch? Or will you use master as the main branch with gh-pages being where big releases are pushed?

**Comment by enthusiast94** [comment]
Just wanted to fix the master branch first. Now i'll rebase dev to master and then start working on it.

**Comment by enthusiast94** [comment]
Ok so I think it would be better to have feature branches. I'll create a new Card UI branch and eventually merge it with master when done.

**Comment by enthusiast94** [comment]
Card UI is now ready. You can test it by checking out card-ui branch.

**Comment by RedRiderX** [comment]
Great job adding that, definitely adds to it.

**Pull request merged**
